# Generated by Django 4.2.7 on 2023-12-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email_or_mobile', models.CharField(help_text='Enter either email or mobile', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
