# Generated by Django 4.2.7 on 2023-12-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webformapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='choice_field',
            field=models.CharField(choices=[('Active Ant', 'Active Ant'), ('Speedy Sparrow', 'Speedy Sparrow'), ('Electric Elephant', 'Electric Elephant')], default='Active Ant', max_length=50),
        ),
    ]
