# Generated by Django 4.2.7 on 2023-12-17 07:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webformapp', '0002_formdata_choice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
