# Generated by Django 4.2.7 on 2023-12-17 07:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webformapp', '0003_alter_formdata_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='choice_field',
        ),
        migrations.AlterField(
            model_name='formdata',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='IN', max_length=2, null=True),
        ),
    ]
