# Generated by Django 4.2.7 on 2023-12-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webformapp', '0004_remove_formdata_choice_field_alter_formdata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='radio_buttons',
            field=models.CharField(blank=True, choices=[('Active Ant', 'Active Ant'), ('Speedy Sparrow', 'Speedy Sparrow'), ('Electric Elephant', 'Electric Elephant')], max_length=50, null=True),
        ),
    ]
